version: "3.8"

name: dofast-system

services:

  admin:
    container_name: dofast-admin
    build:
      context: .
      args:
        NODE_ENV:
          ENV=${NODE_ENV:-production}
          PUBLIC_PATH=${PUBLIC_PATH:-/}
          VUE_APP_TITLE=${VUE_APP_TITLE:-澳美MES系统}
          VUE_APP_BASE_API=${VUE_APP_BASE_API:-/prod-api}
          VUE_APP_APP_NAME=${VUE_APP_APP_NAME:-/}
          VUE_APP_TENANT_ENABLE=${VUE_APP_TENANT_ENABLE:-true}
          VUE_APP_CAPTCHA_ENABLE=${VUE_APP_CAPTCHA_ENABLE:-true}
          VUE_APP_DOC_ENABLE=${VUE_APP_DOC_ENABLE:-true}
          # VUE_APP_BAIDU_CODE=${VUE_APP_BAIDU_CODE:-fadc1bd5db1a1d6f581df60a1807f8ab}
    image: dofast-admin
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - dofast-network

networks:
  dofast-network:
    driver: bridge
